### ISSUE TITLE
Upgrade clean-css to version 4.1.11 or later.

### ISSUE THREAD

**Issue by mirkobrombin** [biskuitorg/biskuit#53]
WS-2019-0017

Vulnerable versions: < 4.1.11
Patched version: 4.1.11
Version of clean-css prior to 4.1.11 are vulnerable to Regular Expression Denial of Service (ReDoS). Untrusted input may cause catastrophic backtracking while matching regular expressions. This can cause the application to be unresponsive leading to Denial of Service.

**Comment by pietrodicaprio** [comment]
The package is present only in package-lock.json
No reference in package.json
Do we really require it?

**Comment by mirkobrombin** [comment]
package-lock.json has priority over package.json during installation

**Comment by tobbexiv** [comment]
Clean-css is required by html-minifier which is required by vue-html-loader which we require. As soon as Vue is upgraded to version 2 (including all Vue related dependencies), this issue should be gone.

**Comment by pietrodicaprio** [comment]
Thank you for the clarification @tobbexiv !
Shall we update it anyway as suggested by the bot? Do you see any issue/benefit?

**Comment by tobbexiv** [comment]
Here I would not do anything. My next plan is to upgrade Vue (#55) to have many dependencies on the latest version. Once this is done, I would look into upgrading Uikit (#43).
