### ISSUE TITLE
Upgrade Vue to 2.x

### ISSUE THREAD

**Issue by tobbexiv** [biskuitorg/biskuit#55]
Vue should be upgraded to version 2.x to avoid issues with required npm dependencies.

This will most likely break the support of most pagekit extensions as they depend on Vue 1.x.

Status (checked = completely finished):
- [x] Debug bar
- [x] Installer
- [x] Marketplace / Extension & Theme handling
- [X] Updater
- [x] Cache
- [x] Captcha
- [x] Dashboard
- [x] Editor
- [x] Finder
- [x] Info
- [x] Mail
- [x] Settings
- [x] Site
- [x] Theme
- [x] User
- [x] Widget
- [x] Package: Biskuit/Blog
- [x] Theme: Biskuit/Butter
- [x] Core
- [x] Main Webpack file

**Comment by mirkobrombin** [comment]
Once updated to vue 2 we should specify it here: https://github.com/biskuitorg/migrate-extension

**Comment by pietrodicaprio** [comment]
Please @mirkobrombin open a new branch for that

**Comment by pietrodicaprio** [comment]
Branch dedicated to this migration: https://github.com/biskuitorg/biskuit/tree/vue-2

**Comment by mirkobrombin** [comment]
With the update, the themes will also have to be made compatible to vue 2.0

**Comment by tobbexiv** [comment]
I added a checklist to track the current status in the first post.

Additional remarks:
* I had to choose something ne w to handle central event broadcasting and chose vue-event-manager.
* I repaired the rss reading widget by using rss-reader. It is now possible to read RSS feeds again if CORS allows this (or a proxy is used). Might need rework.
* The Google Api to get information on the timezone for the location widget requires now an account and billing information. I disabled this code and rework is needed.

**Comment by mirkobrombin** [comment]
> I added a checklist to track the current status in the first post.
> 
> Additional remarks:
> 
> * I had to choose something new to handle central event broadcasting and chose vue-event-manager.
> * I repaired the rss reading widget by using rss-reader. It is now possible to read RSS feeds again if CORS allows this (or a proxy is used). Might need rework.
> * The Google Api to get information on the timezone for the location widget requires now an account and billing information. I disabled this code and rework is needed.

Google API are not essential, not at the moment at least.

**Comment by tobbexiv** [comment]
I finally finished the upgrade to Vue 2. I hopefully tested everything, but due to the size of the changes it might be that I missed something. Thus, I would appreciate if you could also do some testing after the changes are merged and you upgraded your installation using `npm install`.

**Comment by mirkobrombin** [comment]
I will do the first tests this weekend

**Comment by mirkobrombin** [comment]
> I will do the first tests this weekend

I tried to install and everything works correctly. We can start planning the extension conversion and finish marketplace.

**Comment by tobbexiv** [comment]
I would suggest to also do the Uikit upgrade before migrating the extensions as this also leads to changes in extensions.

**Comment by mirkobrombin** [comment]
I completely forgot about this

**Comment by websmurf** [comment]
Just wanted to let you know that I greatly appreciate your effort into creating a continuation of PageKit. 

Unfortunately I don't have much time at this moment to chip in some time, but I'm hoping after the holiday rush things will become a bit easier.

**Comment by mirkobrombin** [comment]
Since the update to Vue.js 2 is complete and the next step is the update to Uikit 3, I'm closing this issue and moving to #43 
I still keep the issue in the pinned.
