### ISSUE TITLE
When I upgrade from Pagekit, it shows "Whoops, looks like something went wrong."

### ISSUE THREAD

**Issue by jebofponderworthy** [biskuitorg/biskuit#75]
I cd into the pagekit folder and unpack the latest release on top, and get that error message.  I'm on Ubuntu 20.04 LTS.  Any idea what I should be looking for to make it work?

**Comment by mirkobrombin** [comment]
Which of the two release versions are you using?

Normal release or webhosting release?

**Comment by jebofponderworthy** [comment]
I tried both.  I use VirtualMin, so I applied the normal release, got the result, removed the site altogether, restored it again, applied webhosting release, got the result, removed it altogether, and restored again to original.

**Comment by mirkobrombin** [comment]
Set `debug true` in your config.php and show me the error log please.

**Comment by mirkobrombin** [comment]
Closed for cleaning. Reopen if you still have the problem.
