### ISSUE TITLE
theme exceptions

### ISSUE THREAD

**Issue by ogmo0n** [biskuitorg/biskuit#77]
After using the pagekit .htaccess for apache and correcting the vue loader issue, I am getting a NoConfigurationException and a NotFoundException for a route when I attempt to visit the homepage of my site. This is with the 1.0.19 version. I just created a clean install using 1.0.18 and had no issues whatsoever.

**Comment by ogmo0n** [comment]
![Screen Shot 2020-08-24 at 12 48 44 PM](https://user-images.githubusercontent.com/24468470/91072863-2601cb00-e608-11ea-9738-aa07b7d938fa.png)
![Screen Shot 2020-08-24 at 12 49 00 PM](https://user-images.githubusercontent.com/24468470/91072879-3023c980-e608-11ea-8d0d-7a1d02c4ece7.png)

**Comment by mirkobrombin** [comment]
This doesn't seem like an error caused by `htaccess`.
What exact problem did you correct? Are you using our htaccess or pagekit one?

**Comment by ogmo0n** [comment]
Correct. This is not related to .htaccess. I used the pagekit .htaccess because I am on an apache server.
I ran into a bunch of issues right out of the gate and thought I had everything fixed until I tried to visit the non-admin side of the site.

**Comment by mirkobrombin** [comment]
Are you using the webhosting package?

**Comment by ogmo0n** [comment]
No. I installed from source (cloned the repo).

**Comment by ogmo0n** [comment]
It appears the instructions for installation have changed since Friday...

**Comment by ogmo0n** [comment]
I am trying again from the webhosting package and so far the install has been much smoother.

**Comment by tobbexiv** [comment]
If you used the dev branch, then the changes to upgrade vue and change the namespace to biskuit are already there which could cause the issues.

**Comment by ogmo0n** [comment]
That's what I was thinking up until a moment ago. I did a clean install using the webhosting version, ran composer install, updated some permissions, and everything was working. Checked the homepage and it was there. I copied my theme into the project packages, enabled it in the system settings, and checked the homepage again. It was there but I made a mental note that I would need to fix something with uikit - everything was working. Then, from the admin, I added my site logo and favicon, saved it, and when I reloaded the homepage, it broke with the same two errors from above.

**Comment by ogmo0n** [comment]
I also enabled the debug options and disabled the cache.

**Comment by ogmo0n** [comment]
Ok, I figured it out. If I disable Home under Pages, the site breaks.

**Comment by tobbexiv** [comment]
But then only the main page should break and other pages should still work.

**Comment by ogmo0n** [comment]
The admin pages continued to work. I had disabled it thinking that it would just remove the default content and not remove the route. Whoops!
