### ISSUE TITLE
Still Pagekit Like issues Google Analytics No mOre Working

### ISSUE THREAD

**Issue by SwapnilAkolkar** [biskuitorg/biskuit#94]
I came accross biscuit cms for adding analytics to admin dashboard and also saw some update development in the gthub , but still I found the Analytics even not work in biscuit cms too. I big thing atleast pagekit shows that Analytics extension in add menu thats absent in biscuit cms.

**Comment by SwapnilAkolkar** [comment]
Also the New feed not working, why then new cms under Biscuit name , its nothing but only Pagekit cms. NO any fix and updates

**Comment by mirkobrombin** [comment]
Here you can find all the NO FIX you are talking about: https://github.com/biskuitorg/biskuit/tree/uikit-3

**Comment by tobbexiv** [comment]
The Pagekit team stopped working on updates of Pagekit. To continue development, a new solution had to be found. As we cannot continue using the name / brand Pagekit, a renaming had to take place. That's the reason why now Biskuit is used as name. To catch up with 4 years of development standstill, some investment is required (upgrade of Vue, upgrade of UIkit, additional corrections / fixes, ...).

So, as a first step, a rebranding took place. Now, the upgrade of the other components is ongoing. Once this is finished, a new Marketplace can be set up and updated versions of the apps will be available.

So, you're right. The current version has only very little differences to Pagekit (even thus there are some which you can see in the changelogs). Future versions will be improved and provide a better experience along with fixes.

**Comment by SwapnilAkolkar** [comment]
Happy to hear ..
